stages:
  - build
  - test
  - report

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# 必要なら以下のようにテスト前に実行するコマンド類を記載する
#before_script:
#  - apt-get update -qq
#  - apt-get install -y cmake g++ python3 python3-pip
#  - pip3 install -r requirements.txt

build:
  stage: build
  script:
    - bash build.sh
  artifacts:
    paths:
      - build/

static_analysis:
  stage: test
  script:
    - ./run_static_analysis.sh
  artifacts:
    paths:
      - reports/static_analysis_report.txt

unit_test:
  stage: test
  script:
    - ./run_coverage_tests.sh
  artifacts:
    paths:
      - reports/unit_test_report.txt

state_transition_test:
  stage: test
  script:
    - ./run_state_transition_tests.sh
  artifacts:
    paths:
      - reports/state_transition_test_report.txt

functional_test:
  stage: test
  script:
    - ./run_functional_tests.sh
  artifacts:
    paths:
      - reports/functional_test_report.txt

check_report_diff:
  stage: report
  script:
    - python3 scripts/check_report_diff.py
  artifacts:
    paths:
      - reports/report_diff_result.txt

notify:
  stage: report
  script:
    - if grep -q "No differences" reports/report_diff_result.txt; then
        echo "No differences detected. Merging...";
        git merge $CI_COMMIT_REF_NAME;
      else
        echo "Differences detected. Sending email notification...";
        echo "CI/CD pipeline detected differences. Please review the reports." | mail -s "CI/CD Pipeline Notification" your_email@example.com;
      fi
